version: "3"
services:
  employee-jdbc:
    image: demo:0.0.1-SNAPSHOT
    ports:
      - "8082:8082"
    networks:
      - network-mysql
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    networks:
      - network-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb  

networks:
  network-mysql: